### ISSUE TITLE
Setup Wifi on Raspberry Pi for demo

### ISSUE THREAD

**Issue by HendrikVE** [HendrikVE/swp-telematik-ws-20-21#10]
For the demo, we will need a network for all our devices. The enterprise network at the FU is not a good option, because we would need another Wifi library on the ESP32. Instead, we should setup a demo network from the Raspberry Pi. Use the following instructions: https://thepi.io/how-to-use-your-raspberry-pi-as-a-wireless-access-point/

**Comment by Moritzw** [comment]
started a wiki entry, currently working on setting up a test network

**Comment by Moritzw** [comment]
wiki entry finished, testing still needed

**Comment by HendrikVE** [comment]
It's working for all of us. We should add this also in form of a script later.

**Comment by HendrikVE** [comment]
Testing finished.
