### ISSUE TITLE
Attack via energy depletion

### ISSUE THREAD

**Issue by Moritzw** [HendrikVE/swp-telematik-ws-20-21#4]
Try to generate higher energy consumption of the ESP to deplete the batteries charge.

**Comment by HendrikVE** [comment]
Difficult to create a demo showing this, at least if the demo should not last longer than ~ two minutes.

**Comment by Moritzw** [comment]
preparing wiki entry, can be explained with some posters even if a live demonstration is not feasible

**Comment by HendrikVE** [comment]
Won't be implemented.
