### ISSUE TITLE
Attack via unsecured MQTT

### ISSUE THREAD

**Issue by Moritzw** [HendrikVE/swp-telematik-ws-20-21#5]
Add unknown esp32 in to the network and transmit faulty data of a window state to openhab.

**Comment by HendrikVE** [comment]
We decided to simply give another esp32 the certificates needed for access to the mqtt broker. For the demo user it will be the same behaviour, but we don't have to weaken or reconfigure the mosquitto installation on the rapsberry pi between the different attacks.

**Comment by leonPreus** [comment]
added spam attack and made it toggleable under make menuconfig, sensor config, sensor 1(bf6a1316ac98cf91924e1ec706fff72d3d6b24f9)
