### ISSUE TITLE
Fast and easy project setup

### ISSUE THREAD

**Issue by Moritzw** [HendrikVE/swp-telematik-ws-20-21#6]
Fast and easy setup of the project with scripts and other utilities.

Open tasks:
- [ ] scripts for radio interference attack
- [x] scripts for secure boot attack
- [x] scripts and templates for openhab (sitemaps etc.)

**Comment by HendrikVE** [comment]
First part of automation is done:
- update of existing scripts (3ae8e91f0bf9f28509e48cced0e2552efd644ebd)
- initialization script for ESP32 codebase (3587b2dc6f2cf195a5f9c31e37075ef99001921c)
- script for CA (12b43cd8a165756e349caea40e2920efd2ae0ae4)
- script for Mosquitto (43c495247b15f1dc293ff487e7ea98bb60b22f4c)
- README about how to use these scripts (766a457ad2aab6650f3fb9fb3c9a5b2d33d45eee)

**Comment by leonPreus** [comment]
added script for OTA server(ae1c5c74dea2f9cb89197c28b127a5f0090f5046)

**Comment by HendrikVE** [comment]
script and files for openhab provided with 7b58e0a101a213c58df8d5a6460c02daac38e850

**Comment by Moritzw** [comment]
testing is finished, seems to be working fine now
